package com.interviewbridge.dto.response;

/**
 * Response payload representing an individual question generated by the AI engine.
 */
public record AIQuestionResponse(
    int questionNumber,
    String questionText,
    String referenceAnswer
) {}
