package com.interviewbridge.response;

/**
 * Response payload representing an individual question generated by the AI engine.
 */
public record AIQuestionResponse(
    int questionNumber,
    String questionText
) {}
